#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument

if [[ -z "$1" ]]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
# Ping the provided IP address 5 times
    ping -c 5 "$1"
fi
